### ISSUE TITLE
Add various topics for greater exposure to the DNN Community

### ISSUE THREAD

**Issue by david-poindexter** [alex-pommier/DNN-DynamicTruncateEventLogs#1]
@alex-pommier you may want to add the following topics to your repository for greater exposure within the DNN Community:

* `dnncms`
* `dnn`
* `dotnetnuke`

Let me know if you need any help with how to do this.

**Comment by alex-pommier** [comment]
Thanks @david-poindexter all done!

**Comment by david-poindexter** [comment]
Awesome @alex-pommier 🎉
